version: "3.4"

services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/var/www
    ports:
      - 8080:8080
    environment:
      APP_DEBUG: 'true'

  mariadb:
    image: "mariadb:jammy"
    volumes:
      - "./app:/app"
      - "./docker/mariadb/data:/var/lib/mysql"
      - "./docker/mariadb/logs:/var/log/mysql"
      - "./docker/mariadb/conf:/etc/mysql"
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
