kernel:
    resource: ../src/Kernel.php
    type: annotation

user-list:
    path: /user/list
    controller: App\Controller\ListUserController
    methods: GET

user-find:
    path: /user/{uuid}
    controller: App\Controller\FindUserController
    methods: GET

user-create:
    path: /user/create
    controller: App\Controller\CreateUserController
    methods: POST
